# Generated by Django 6.1.2 on 2026-10-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
